# Generated by Django 5.2.1 on 2025-06-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='barangay',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='company_address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='municipality',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='ojt_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='ojt_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='province',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='time_of_log',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
