# Generated by Django 5.2.1 on 2025-06-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_alter_student_barangay_alter_student_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('BSIT', 'BSIT'), ('BSCS', 'BSCS'), ('BSBA', 'BSBA')], max_length=50),
        ),
    ]
