# Generated by Django 5.2.1 on 2025-06-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_remove_student_full_name_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.CharField(choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026')], default='Uknown', max_length=9),
            preserve_default=False,
        ),
    ]
