# Generated by Django 5.2.1 on 2025-06-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0005_student_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.CharField(choices=[('2021-2022', '2021-2022'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2026-2027', '2026-2027')], max_length=9),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('BSCS', 'Bachelor of Science in Computer Science'), ('BSIT', 'Bachelor of Science in Information Technology')], max_length=50),
        ),
    ]
