# Generated by Django 5.2.1 on 2025-06-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0006_alter_student_academic_year_alter_student_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('BSAIS', 'BSAIS'), ('BSIT', 'BSIT'), ('BSCRIM', 'BSCRIM'), ('BSOA', 'BSOA'), ('BEED', 'BEED'), ('BSED', 'BSED'), ('BSTM', 'BSTM')], max_length=50),
        ),
    ]
