# Generated by Django 5.2.1 on 2025-06-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0007_student_email_alter_student_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
