# Generated by Django 5.2.1 on 2025-06-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0015_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('program', models.CharField(choices=[('BSAIS', 'BSAIS'), ('BSIT', 'BSIT'), ('BSCRIM', 'BSCRIM'), ('BSOA', 'BSOA'), ('BEED', 'BEED'), ('BSED', 'BSED'), ('BSTM', 'BSTM')], max_length=50)),
                ('academic_year', models.CharField(choices=[('2021-2022', '2021-2022'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2026-2027', '2026-2027')], max_length=9)),
                ('barangay', models.CharField(max_length=50)),
                ('municipality', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('company_placement', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=150)),
                ('designated', models.CharField(max_length=100)),
                ('ojt_start', models.DateTimeField()),
                ('ojt_end', models.DateTimeField()),
                ('total_hours', models.IntegerField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
