# Generated by Django 5.2.1 on 2025-06-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0016_archivedstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id_number', models.CharField(max_length=50)),
                ('student_full_name', models.CharField(max_length=255)),
                ('evaluator_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('punctuality', models.IntegerField()),
                ('work_quality', models.IntegerField()),
                ('communication_skills', models.IntegerField()),
                ('teamwork', models.IntegerField()),
                ('final_grade', models.DecimalField(decimal_places=2, max_digits=4)),
                ('letter_grade', models.CharField(max_length=4)),
                ('comments', models.TextField(blank=True)),
                ('date_evaluated', models.DateField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
